sky:
  jwt:
    #管理端jwt信息
    admin-secret-key: itcast           # 设置jwt签名加密时使用的秘钥
    admin-ttl: 1296000000              # 设置jwt过期时间 15天
    admin-token-name: token            # 设置前端传递过来的令牌名称
    #移动端jwt信息
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl: 1296000000

minio:
  endpoint: http://127.0.0.1:9090 #Minio服务所在地址
  bucketName: sky-take-out #存储桶名称
  accessKey: Mkq2NvS3ijP2rVyNiNPT #访问的key
  secretKey: HPA2hP289vNst7jUA8fALib1ydgOxWpi8kyowncf #访问的秘钥

wechat:
  #微信小程序信息
  appid: wxa207b007c4fe4673
  secret: a6528a669f56834ae663d26037391c74

  #微信支付信息（未获取，以下为假数据）
  mchid: 1561414331
  mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
  apiV3Key: CZBK51236435wxpay435434323FFDuv3
  privateKeyFilePath: D:\project\java\sky-take-out\sky-server\src\main\resources\apiclient_key.pem
  weChatPayCertFilePath: D:\project\java\sky-take-out\sky-server\src\main\resources\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
  notifyUrl: https://14164a59.cpolar.io/notify/paySuccess  # 内网穿透地址，支付成功回调地址
  refundNotifyUrl: https://14164a59.cpolar.io/notify/refundSuccess # 内网穿透地址，退款成功回调地址
